#!/bin/sh

cd ../wxWidgets

cpus=`sysctl -n hw.ncpu`

# Build wxWidgets on mac
mkdir build-macOS
cd build-macOS
../configure --enable-debug --enable-universal-binary=x86_64,arm64 --disable-sys-libs
make -j$cpus